//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xmlsystemEntities : DbContext
    {
        public xmlsystemEntities()
            : base("name=xmlsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mlregistration> mlregistrations { get; set; }
        public virtual DbSet<courselist> courselists { get; set; }
        public virtual DbSet<crud_test1> crud_test1 { get; set; }
    }
}
